"use client";
import { useState } from "react";
import { motion } from "framer-motion";
import { profile } from "../../content/profile";import { career } from "../../content/career";import { projects } from "../../content/projects";import { thinking } from "../../content/thinking";import { interests } from "../../content/interests";import { contact } from "../../content/contact";import { operatingProgression } from "../../content/timeline";
import { MainNav } from "../navigation/MainNav";import { HeroPortrait } from "../avatar/HeroPortrait";import { AvatarProvider, useAvatarState } from "../avatar/useAvatarState";import { AvatarSection } from "../avatar/AvatarController";import { SectionLabel } from "../ui/SectionLabel";import { LargeTitle } from "../ui/LargeTitle";import { ProjectCaseStudy } from "../projects/ProjectCaseStudy";import { InventoryInvestigation } from "../projects/InventoryInvestigation";import { CopilotDemo } from "../projects/CopilotDemo";
function Experience(){const{setState}=useAvatarState();const[think,setThink]=useState(0);return <main><MainNav/>
 <AvatarSection id="top" state="greeting" className="hero"><div className="heroKicker">{profile.eyebrow.replaceAll("·","  ·  ")}</div><h1>SI <span>PEI</span></h1><HeroPortrait/><div className="heroStatement"><SectionLabel number="00" label="HELLO"/><h2>I BUILD BETTER<br/><em>OPERATING SYSTEMS.</em></h2><div className="heroBottom"><p>{profile.support}</p><a href="#work">Explore my work <span>↘</span></a></div></div><div className="progression"><span>Operations</span><b>→</b><span>Systems</span><b>→</b><span>AI</span></div><p className="scrollHint">SCROLL TO EXPLORE <span>↓</span></p></AvatarSection>
 <AvatarSection id="about" state="idle" className="about section"><SectionLabel number="01" label="ABOUT"/><LargeTitle outline>WHO IS SI?</LargeTitle><div className="aboutGrid"><p className="lead">A career progressing toward increasingly higher-level operating problems.</p><div className="pillars">{profile.pillars.map((p,i)=><div key={p}><span>0{i+1}</span><strong>{p}</strong></div>)}</div></div><div className="journey">{profile.arc.map((x,i)=><span key={x}>{x}{i<profile.arc.length-1&&<b>→</b>}</span>)}</div><div className="operatingArc">{operatingProgression.map((x,i)=><div key={x}><span>{i+1}</span><p>{x}</p></div>)}</div></AvatarSection>
 <AvatarSection id="career" state="presenting" className="career section dark"><SectionLabel number="02" label="EXPERIENCE"/><LargeTitle>OPERATOR</LargeTitle><p className="sectionIntro">Execution taught me the work. Leadership taught me the system.</p><div className="careerList">{career.map((c)=><article key={c.period} onMouseEnter={()=>setState("presenting")}><span style={{background:c.accent}}>{c.period}</span><div><p>{c.category}</p><h3>{c.title}</h3></div><ul>{c.focus.map(f=><li key={f}>{f}</li>)}</ul><b>↗</b></article>)}</div></AvatarSection>
 <AvatarSection id="work" state="working" className="work section"><SectionLabel number="03" label="SELECTED WORK"/><div className="workTitle"><LargeTitle>PROOF,<br/><em>NOT CLAIMS.</em></LargeTitle><p>Problem → Evidence → Analysis → Root Cause → Intervention → Impact → Lessons</p></div><ProjectCaseStudy project={projects[0]}/><ProjectCaseStudy project={projects[1]}/><article className="inventoryCase"><div className="caseTop"><span>03 / INVENTORY ACCURACY</span><div><i>RCA</i><i>AI BRIDGE</i></div></div><h3>Finding the Error<br/>Behind the Number</h3><p>A variance is a symptom. Investigate the operating system that produced it.</p><InventoryInvestigation/></article><div className="projectIndex">{projects.slice(3).map(p=><article key={p.id} onMouseEnter={()=>setState(p.id==="copilot"?"working":"looking")}><span>{p.number}</span><div><p>{p.title}</p><h3>{p.headline}</h3><small>{p.tags.join(" · ")}</small></div><b>↗</b></article>)}</div></AvatarSection>
 <AvatarSection id="thinking" state="thinking" className="thinking section dark"><SectionLabel number="04" label="HOW I THINK"/><LargeTitle>THINK</LargeTitle><div className="thinkingLayout"><div className="thinkNav">{thinking.map((t,i)=><button key={t.title} className={i===think?"active":""} onClick={()=>setThink(i)}><span>0{i+1}</span>{t.title}<b>→</b></button>)}</div><motion.div key={think} className="thinkDetail" initial={{opacity:0,y:16}} animate={{opacity:1,y:0}}><span>FRAMEWORK / 0{think+1}</span><h3>{thinking[think].title}</h3><p>{thinking[think].idea}</p>{thinking[think].flow&&<div>{thinking[think].flow?.map((x,i)=><span key={x}>{x}{i<(thinking[think].flow?.length||0)-1&&<b>→</b>}</span>)}</div>}</motion.div></div></AvatarSection>
 <AvatarSection id="building" state="working" className="building section"><SectionLabel number="05" label="BUILDING NOW"/><LargeTitle>BUILD</LargeTitle><div className="buildIntro"><h3>From improving existing systems<br/>to building new ones.</h3><p>Builder exploring a thesis at the intersection of AI and physical operations.</p></div><div className="themes">{["AI + Physical Operations","Inventory Exception Copilot","AI Native 3PL","Operations Intelligence"].map((x,i)=><span key={x}>0{i+1} / {x}</span>)}</div><CopilotDemo/></AvatarSection>
 <AvatarSection id="beyond" state="casual" className="beyond section"><SectionLabel number="06" label="BEYOND WORK"/><LargeTitle>STILL<br/><em>CURIOUS.</em></LargeTitle><div className="interestGrid">{interests.map((x,i)=><article key={x.name}><span>0{i+1}</span><h3>{x.name}</h3><p>{x.detail}</p><b>↗</b></article>)}</div></AvatarSection>
 <AvatarSection id="contact" state="greeting" className="contact section dark"><SectionLabel number="07" label="CONTACT"/><h2>LET’S BUILD<br/><em>SOMETHING BETTER.</em></h2><div className="contactGrid">{contact.contexts.map(c=><div key={c.title}><h3>{c.title}</h3><p>{c.copy}</p></div>)}</div><div className="contactBottom"><div>{contact.links.map(l=><a key={l.label} href={l.href}>{l.label} ↗</a>)}</div><p>SI PEI © 2026<br/>LOS ANGELES, CA</p></div></AvatarSection>
 </main>}
export function SiteExperience(){return <AvatarProvider><Experience/></AvatarProvider>}
