import type { Project } from "./types";
export const projects: Project[] = [
 {id:"amazon",number:"01",title:"Amazon AFE Productivity",headline:"Scaling Warehouse Productivity",problem:"Packing productivity was constrained by material support processes.",evidence:["88 UPH — editable content","Associate feedback","Cross-shift analysis"],analysis:["Fishbone analysis","Pareto analysis"],rootCause:"Material support / Water Spider process bottleneck.",intervention:["Redesigned the material support process","Standardized operating procedures and training"],metrics:[{value:"+20%",label:"Productivity",editable:true},{value:"+50%",label:"Support efficiency",editable:true},{value:"$MM",label:"Annualized operational impact",editable:true}],lessons:["Improving the constraint changes the whole system."],tags:["AMAZON","LEAN","OPERATIONS"]},
 {id:"returns",number:"02",title:"Returns Process Redesign",headline:"From Five Days to Eight Hours",problem:"A fragmented returns workflow created delays and weak operational control.",evidence:["5 DAYS — before","8 HOURS — after"],analysis:["Workflow mapping","Handoff review"],rootCause:"A workflow bottleneck across ownership and control points.",intervention:["Redesigned the end-to-end process","Introduced operational controls"],metrics:[{value:"5 DAYS → 8 HOURS",label:"Cycle time transformation",editable:true}],lessons:["Speed follows clarity of ownership."],tags:["RETURNS","PROCESS","CONTROL"]},
 {id:"inventory",number:"03",title:"Inventory Accuracy",headline:"Finding the Error Behind the Number",problem:"A variance is a symptom. The operating question is what produced it.",evidence:["Expected: 100","Actual: 87","Variance: −13"],analysis:["Exception classification","Transaction trail"],intervention:["Trace the error path","Assign the corrective control"],metrics:[],lessons:["Investigation should create reusable evidence."],tags:["INVENTORY","RCA","AI BRIDGE"]},
 {id:"network",number:"04",title:"Multi-Site Operations",headline:"One Network. Different Operating Systems.",problem:"Apparently similar warehouses produce different outcomes.",evidence:["LAX · HOU · EWR · ONT · SAV"],analysis:["Compare SLA, accuracy, complaints, throughput and process consistency"],intervention:["Identify operating-system differences across facilities"],metrics:[],lessons:["Standardization begins with understanding local variation."],tags:["3PL","NETWORK","SYSTEMS"]},
 {id:"systems",number:"05",title:"Process / WMS System Design",headline:"Designing Error-Proof Operations",problem:"Frontline errors often reveal missing system controls.",evidence:["OMS → WMS → AMS → Exception → Resolution"],analysis:["Translate operator friction into requirements"],intervention:["Duplicate-label prevention","Tracking validation","Exception workflows"],metrics:[],lessons:["A good requirement connects reality to control."],tags:["WMS","PRODUCT","CONTROLS"]},
 {id:"copilot",number:"06",title:"AI 3PL Operations Copilot",headline:"From Exceptions to Decisions",problem:"Operational teams lose time coordinating, investigating and deciding.",evidence:["Inventory discrepancy","SLA risk","Repeated label exception"],analysis:["Evidence synthesis","Root-cause suggestions"],intervention:["Turn exceptions into recommended actions with owners"],metrics:[],lessons:["AI should reduce decision friction, not hide evidence."],tags:["AI","3PL","PROTOTYPE"]}
];
